name: Build App

on:
  push:
    tags:
      - 'v*.*.*'
    branches: 
      - "master"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-for-spark:
    runs-on: ubuntu-latest
    name: Build for Spark Store
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up directory
      run: |
        mkdir -p build/
        cp -rv deb_template build/
        mkdir -p build/deb_template/opt/netease-cloud-music/resources/app/
        cp -rv ./assets build/deb_template/opt/netease-cloud-music/resources/app/
        cp -v ./package.json build/deb_template/opt/netease-cloud-music/resources/app/
        cp -v ./index.js build/deb_template/opt/netease-cloud-music/resources/app/
        cp -v ./LICENSE build/deb_template/opt/netease-cloud-music/resources/app/

        STRIPPED_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[", ]//g')
        # 替换版本号
        sed -i "s/%VERSION%/$STRIPPED_VERSION/g" "build/deb_template/DEBIAN/control"
        # 替换软件包大小
        app_size=$(du -sh --block-size=1k "build/deb_template" | awk '{print $1}')
        sed -i "s/%INSTALLED_SIZE%/$app_size/g" "build/deb_template/DEBIAN/control"

    - name: Build deb for Spark Store
      run: |
        STRIPPED_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[", ]//g')
        cd build/
        dpkg-deb --build deb_template netease-cloud-music_$(echo $STRIPPED_VERSION)_all.deb

    - name: Upload assets to beta release
      uses: softprops/action-gh-release@v2
      if: contains( github.ref, 'refs/tags')
      with:
        files: | 
          build/netease-cloud-music_*.deb
        prerelease: false
        tag_name:  ${{ github.ref_name }}

  build:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            electron_args: "dist-linux-loong64"
          - os: ubuntu-latest
            electron_args: "dist-linux"
          - os: ubuntu-latest
            electron_args: "dist-linux-arm64"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Node Dependencies
      run: |
        rm -rf deb_template
        electron_use_remote_checksums=1 npm install

    - name: Building Electron App
      run: npm run ${{ matrix.config.electron_args }}

    - name: Upload assets to beta release
      uses: softprops/action-gh-release@v2
      if: contains( github.ref, 'refs/tags')
      with:
        files: | 
          build/*.deb
          build/*.tar.gz
          build/*.AppImage
        prerelease: false
        tag_name:  ${{ github.ref_name }}